import { NextRequest, NextResponse } from "next/server";

const subheads = {
  pt: [
    { id: 1, text: "Faturação certificada + rotina fiscal organizada." },
    { id: 2, text: "IVA e SS com lembretes e automação." },
    { id: 3, text: "Cobertura até 1.500€ (ver termos)." },
    { id: 4, text: "Emite por texto ou voz no WhatsApp." },
    { id: 5, text: "Tudo num só lugar, sem complicações." },
    { id: 6, text: "Para independentes e pequenos negócios." },
    { id: 7, text: "Menos erros. Mais confiança." },
    { id: 8, text: "Sabe sempre o que tens a pagar." },
    { id: 9, text: "Configuração simples. Uso diário rápido." },
    { id: 10, text: "Conformidade sem drama." },
    { id: 11, text: "Automatiza a parte chata." },
    { id: 12, text: "Faturas prontas em segundos." },
    { id: 13, text: "Mais controlo, menos esforço." },
    { id: 14, text: "Proteção quando precisas." },
    { id: 15, text: "Feito para a realidade portuguesa." },
    { id: 16, text: "Um sistema claro e moderno." },
    { id: 17, text: "A tua faturação, sempre em dia." },
    { id: 18, text: "Trabalha com calma." },
    { id: 19, text: "Sem papelada interminável." },
    { id: 20, text: "Uma forma mais inteligente de gerir impostos." },
    { id: 21, text: "WhatsApp-first, porque é o que usas." },
    { id: 22, text: "Certificada e preparada para PT." },
    { id: 23, text: "Rotina fiscal em piloto automático." },
    { id: 24, text: "Menos tarefas repetidas." },
    { id: 25, text: "Um escudo extra para a tua atividade." },
    { id: 26, text: "Tudo explicado, sem linguagem difícil." },
    { id: 27, text: "Começa grátis e mantém simples." },
    { id: 28, text: "Mais tempo para clientes." },
    { id: 29, text: "Zero complicação para faturar." },
    { id: 30, text: "Controlo real, todos os dias." },
  ],
  en: [
    { id: 1, text: "Certified invoicing + a calmer tax workflow." },
    { id: 2, text: "VAT & Social Security—automated guidance." },
    { id: 3, text: "Coverage up to €1,500 (terms apply)." },
    { id: 4, text: "Send a text/voice note, get an invoice." },
    { id: 5, text: "Built for Portugal's rules." },
    { id: 6, text: "For freelancers & small businesses." },
    { id: 7, text: "Less admin. More time." },
    { id: 8, text: "Know what's due, without guessing." },
    { id: 9, text: "Simple setup. Fast daily use." },
    { id: 10, text: "Compliance without the headache." },
    { id: 11, text: "Automate the repetitive stuff." },
    { id: 12, text: "Invoices ready in seconds." },
    { id: 13, text: "More control, less effort." },
    { id: 14, text: "Protection when you need it." },
    { id: 15, text: "Made for the Portuguese reality." },
    { id: 16, text: "A clear, modern system." },
    { id: 17, text: "Your invoicing, always up to date." },
    { id: 18, text: "Work with peace of mind." },
    { id: 19, text: "No endless paperwork." },
    { id: 20, text: "A smarter way to manage taxes." },
    { id: 21, text: "WhatsApp-first, because that's what you use." },
    { id: 22, text: "Certified and ready for PT." },
    { id: 23, text: "Tax routine on autopilot." },
    { id: 24, text: "Fewer repetitive tasks." },
    { id: 25, text: "An extra shield for your business." },
    { id: 26, text: "Everything explained, no jargon." },
    { id: 27, text: "Start free and keep it simple." },
    { id: 28, text: "More time for clients." },
    { id: 29, text: "Zero hassle invoicing." },
    { id: 30, text: "Real control, every day." },
  ],
};

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const lang = (searchParams.get("lang") || "pt") as "pt" | "en";

  return NextResponse.json(subheads[lang] || subheads.pt);
}
